// 튜토리얼(/study/tutorial) 전용 더미 데이터.
// 실제 컴포넌트(MessageBubble·ProductGrid·CurrentUnderstandingPanel)에 그대로 주입해
// "진짜 화면과 동일한" 데모를 만들기 위한 고정 fixture — 백엔드 호출 없음.

import { Conflict, Impression, PreferenceState, Turn } from "@/lib/types";

const T0 = "2026-01-01T00:00:00Z";

export const tutorialTurns: Turn[] = [
  {
    id: "demo_u1",
    sessionId: "demo",
    turnIndex: 1,
    role: "user",
    content: "친구 생일 선물로 무선 이어폰이나 스마트워치를 고민 중이에요. 너무 싸 보이지 않으면 좋겠어요.",
    intentLabels: [],
    relatedProductIds: [],
    createdAt: T0,
  },
  {
    id: "demo_a1",
    sessionId: "demo",
    turnIndex: 2,
    role: "service_agent",
    content:
      "말씀해주신 기준대로 세 가지 다른 방향의 상품을 보여드릴게요. 카드의 좋아요/싫어요로 반응해주시면 기준을 더 정확하게 잡을 수 있어요.",
    agentAction: "recommend",
    intentLabels: [],
    relatedProductIds: ["demo_p1", "demo_p2", "demo_p3"],
    createdAt: T0,
  },
];

export const tutorialImpressions: Impression[] = [
  {
    id: "demo_imp1",
    turnId: "demo_a1",
    productId: "demo_p1",
    rank: 0,
    recommendationReason: "가성비와 평점 균형이 좋아 선물용으로 무난해요.",
    matchedIntentions: ["평점이 믿을 만해요", "선물로 무난한 가격대"],
    weakIntentions: ["디자인은 호불호가 있을 수 있어요"],
    createdAt: T0,
    product: {
      id: "demo_p1",
      title: "노이즈캔슬링 무선 이어폰 (화이트)",
      category: "전자기기",
      brand: "사운드웨이브",
      price: 89000,
      discountRate: 0.1,
      deliveryFee: 0,
      rating: 4.6,
      reviewCount: 1240,
      longTermReviewRatio: 0.42,
      recentSalesCount: 320,
      sellerName: "사운드웨이브 공식스토어",
      sellerGrade: "빅파워",
      attributes: { 색상: "화이트", 노이즈캔슬링: true, 충전: "USB-C" },
      description: "노이즈캔슬링과 준수한 음질을 갖춘 무난한 선물용 이어폰.",
      cueSummary: {
        priceCue: "mid",
        trustCue: "high",
        popularityCue: "popular",
        sellerCue: "trusted",
        noveltyCue: "common",
      },
    },
  },
  {
    id: "demo_imp2",
    turnId: "demo_a1",
    productId: "demo_p2",
    rank: 1,
    recommendationReason: "흔하지 않은 모델이라 특별한 선물 느낌을 줄 수 있어요.",
    matchedIntentions: ["특별해 보이는 디자인", "기능이 다양해요"],
    weakIntentions: ["가격대가 조금 높아요"],
    createdAt: T0,
    product: {
      id: "demo_p2",
      title: "GPS 스마트워치 (아몰레드 디스플레이)",
      category: "전자기기",
      brand: "핏라인",
      price: 156000,
      discountRate: 0,
      deliveryFee: 0,
      rating: 4.4,
      reviewCount: 380,
      longTermReviewRatio: 0.28,
      recentSalesCount: 90,
      sellerName: "핏라인 스토어",
      sellerGrade: "파워",
      attributes: { 색상: "그라파이트", GPS: true, 방수: "5ATM" },
      description: "운동 기록과 알림이 풍부한, 디자인이 돋보이는 스마트워치.",
      cueSummary: {
        priceCue: "high",
        trustCue: "medium",
        popularityCue: "moderate",
        sellerCue: "normal",
        noveltyCue: "distinctive",
      },
    },
  },
  {
    id: "demo_imp3",
    turnId: "demo_a1",
    productId: "demo_p3",
    rank: 2,
    recommendationReason: "가격 부담이 적고 최근 많이 팔린 인기 상품이에요.",
    matchedIntentions: ["가격 부담이 적어요", "최근 인기가 많아요"],
    weakIntentions: ["선물로는 조금 가벼워 보일 수 있어요"],
    createdAt: T0,
    product: {
      id: "demo_p3",
      title: "감성 디자인 미니 블루투스 스피커 (크림)",
      category: "전자기기",
      brand: "무드톤",
      price: 49000,
      discountRate: 0.15,
      deliveryFee: 0,
      rating: 4.5,
      reviewCount: 2100,
      longTermReviewRatio: 0.2,
      recentSalesCount: 800,
      sellerName: "무드톤",
      sellerGrade: "파워",
      attributes: { 색상: "크림", 방수: "생활방수", 재생시간: "12시간" },
      description: "가격 부담이 적고 디자인이 무난해 부담 없이 고르기 좋은 인기 모델.",
      cueSummary: {
        priceCue: "low",
        trustCue: "medium",
        popularityCue: "very_popular",
        sellerCue: "normal",
        noveltyCue: "common",
      },
    },
  },
];

export const tutorialPreferenceState: PreferenceState = {
  id: "demo_snap",
  turnIndex: 2,
  stage: "exploring",
  activeTopicIds: ["t_trust", "t_notcheap", "t_design"],
  anchorScores: {
    Functional: 0.7,
    Social: 0.5,
    Emotional: 0.6,
    Epistemic: 0.3,
    Conditional: 0.55,
    Hedonic: 0,
    Utilitarian: 0,
  },
  anchorBreakdown: {
    Functional: {
      confirmedScore: 0.55,
      contributors: [
        {
          topicLabel: "평점·리뷰가 믿을 만함",
          intensity: 0.8,
          confidence: "confirmed",
          evidenceStrength: "high",
          decisionImpact: "high",
          temporalStatus: "active",
          contribution: 0.4,
        },
      ],
    },
  },
  motivationScores: {
    Adventure: 0.3,
    Gratification: 0.35,
    Role: 0.7,
    BargainValue: 0.4,
    SocialShopping: 0.2,
    Idea: 0.3,
    Utilitarian: 0.45,
  },
  hardConstraints: ["평점·리뷰가 믿을 만할 것"],
  softPreferences: ["특별해 보이는 디자인"],
  avoidances: ["너무 저렴해 보이는 인상"],
  priorityOrder: ["t_trust", "t_notcheap", "t_design"],
  uncertainty: {
    unresolvedQuestions: ["예산 상한이 있나요?"],
    ambiguousTopics: ["t_budget"],
    conflictIds: [],
  },
  userVisibleSummary: {
    oneSentenceSummary:
      "선물용으로 평점이 믿을 만하면서 너무 저렴해 보이지 않는 걸 찾고 계신 것 같아요.",
    needsConfirmation: true,
    chips: [
      {
        id: "t_trust",
        label: "평점·리뷰가 믿을 만할 것",
        type: "must_have",
        userEditable: true,
        evidenceCount: 3,
        displayRationale: "여러 번 평점·리뷰를 언급하셨어요.",
      },
      {
        id: "t_notcheap",
        label: "너무 저렴해 보이지 않기",
        type: "important",
        userEditable: true,
        evidenceCount: 2,
        displayRationale: "선물이라 저렴해 보이면 곤란하다고 하셨어요.",
      },
      {
        id: "t_design",
        label: "특별해 보이는 디자인",
        type: "nice_to_have",
        userEditable: true,
        evidenceCount: 1,
        displayRationale: "흔하지 않은 느낌을 선호하셨어요.",
      },
      {
        id: "t_budget",
        label: "예산 20만원 이하?",
        type: "uncertain",
        userEditable: true,
        evidenceCount: 1,
        displayRationale: "아직 예산을 명확히 말씀하지 않으셨어요.",
      },
    ],
  },
  createdAt: T0,
};

export const tutorialConflict: Conflict = {
  id: "demo_conf",
  severity: "ambiguous",
  status: "open",
  conflictType: "가격 vs 인상",
  oldAssumption: "너무 저렴해 보이지 않는 게 중요",
  newSignal: "가격 부담이 적은 쪽에 '좋아요'",
  explanationForUser:
    "앞에서는 '너무 저렴해 보이지 않으면 좋겠다'고 하셨는데, 방금 가격 부담이 적은 상품에 좋아요를 누르셨어요. 어느 쪽을 더 우선할까요?",
  suggestedResolutions: [
    { id: "r1", label: "가격 부담이 적은 쪽을 우선할게요", action: "prefer_new", resultingStatePreview: "예산 절약을 더 중요하게 반영" },
    { id: "r2", label: "그래도 너무 저렴해 보이지 않는 게 우선이에요", action: "keep_old", resultingStatePreview: "선물 인상(저렴해 보이지 않기) 유지" },
    { id: "r3", label: "직접 수정", action: "manual_edit", resultingStatePreview: "기준을 직접 입력" },
  ],
  createdAt: T0,
};
