// 튜토리얼(/study/tutorial) 전용 더미 데이터.
// 실제 컴포넌트(MessageBubble·ProductGrid·CurrentUnderstandingPanel)에 그대로 주입해
// "진짜 화면과 동일한" 데모를 만들기 위한 고정 fixture — 백엔드 호출 없음.

import { Conflict, Impression, PreferenceState, Turn } from "@/lib/types";
import { tr } from "@/lib/studyI18n";

const T0 = "2026-01-01T00:00:00Z";

export const tutorialTurns: Turn[] = [
  {
    id: "demo_u1",
    sessionId: "demo",
    turnIndex: 1,
    role: "user",
    content: tr("친구 생일 선물로 무선 이어폰이나 스마트워치를 고민 중이에요. 너무 싸 보이지 않으면 좋겠어요.", "I am considering wireless earbuds or a smartwatch as a birthday gift for a friend. I do not want it to look too cheap."),
    dialogueActs: [],
    relatedProductIds: [],
    createdAt: T0,
  },
  {
    id: "demo_a1",
    sessionId: "demo",
    turnIndex: 2,
    role: "service_agent",
    content:
      tr("말씀해주신 기준대로 세 가지 다른 방향의 상품을 보여드릴게요. 카드의 좋아요/싫어요로 반응해주시면 기준을 더 정확하게 잡을 수 있어요.", "I will show you three products that approach your criteria in different ways. Use Like or Dislike on the cards to help me refine what matters to you."),
    agentAction: "recommend",
    dialogueActs: [],
    relatedProductIds: ["demo_p1", "demo_p2", "demo_p3"],
    createdAt: T0,
  },
];

export const tutorialImpressions: Impression[] = [
  {
    id: "demo_imp1",
    turnId: "demo_a1",
    productId: "demo_p1",
    rank: 0,
    recommendationReason: tr("가성비와 평점 균형이 좋아 선물용으로 무난해요.", "It offers a balanced combination of value and ratings for a gift."),
    matchedIntentions: tr(["평점이 믿을 만해요", "선물로 무난한 가격대"], ["Reliable ratings", "A reasonable price for a gift"]),
    weakIntentions: tr(["디자인은 호불호가 있을 수 있어요"], ["The design may not appeal to everyone"]),
    createdAt: T0,
    product: {
      id: "demo_p1",
      title: tr("노이즈캔슬링 무선 이어폰 (화이트)", "Noise-canceling Wireless Earbuds (White)"),
      category: tr("전자기기", "Electronics"),
      brand: tr("사운드웨이브", "SoundWave"),
      price: 89000,
      discountRate: 0.1,
      deliveryFee: 0,
      rating: 4.6,
      reviewCount: 1240,
      longTermReviewRatio: 0.42,
      recentSalesCount: 320,
      sellerName: tr("사운드웨이브 공식스토어", "SoundWave Official Store"),
      sellerGrade: tr("빅파워", "Top Seller"),
      attributes: tr<Record<string, string | number | boolean>>({ 색상: "화이트", 노이즈캔슬링: true, 충전: "USB-C" }, { Color: "White", "Noise canceling": true, Charging: "USB-C" }),
      description: tr("노이즈캔슬링과 준수한 음질을 갖춘 무난한 선물용 이어폰.", "Gift-ready earbuds with noise canceling and balanced sound quality."),
      cueSummary: {
        priceCue: "mid",
        trustCue: "high",
        popularityCue: "popular",
        sellerCue: "trusted",
        noveltyCue: "common",
      },
    },
  },
  {
    id: "demo_imp2",
    turnId: "demo_a1",
    productId: "demo_p2",
    rank: 1,
    recommendationReason: tr("흔하지 않은 모델이라 특별한 선물 느낌을 줄 수 있어요.", "Its distinctive design may make the gift feel more special."),
    matchedIntentions: tr(["특별해 보이는 디자인", "기능이 다양해요"], ["Distinctive design", "Wide range of features"]),
    weakIntentions: tr(["가격대가 조금 높아요"], ["Slightly higher price"]),
    createdAt: T0,
    product: {
      id: "demo_p2",
      title: tr("GPS 스마트워치 (아몰레드 디스플레이)", "GPS Smartwatch (AMOLED Display)"),
      category: tr("전자기기", "Electronics"),
      brand: tr("핏라인", "FitLine"),
      price: 156000,
      discountRate: 0,
      deliveryFee: 0,
      rating: 4.4,
      reviewCount: 380,
      longTermReviewRatio: 0.28,
      recentSalesCount: 90,
      sellerName: tr("핏라인 스토어", "FitLine Store"),
      sellerGrade: tr("파워", "Featured Seller"),
      attributes: tr<Record<string, string | number | boolean>>({ 색상: "그라파이트", GPS: true, 방수: "5ATM" }, { Color: "Graphite", GPS: true, "Water resistance": "5 ATM" }),
      description: tr("운동 기록과 알림이 풍부한, 디자인이 돋보이는 스마트워치.", "A distinctive smartwatch with extensive fitness tracking and notifications."),
      cueSummary: {
        priceCue: "high",
        trustCue: "medium",
        popularityCue: "moderate",
        sellerCue: "normal",
        noveltyCue: "distinctive",
      },
    },
  },
  {
    id: "demo_imp3",
    turnId: "demo_a1",
    productId: "demo_p3",
    rank: 2,
    recommendationReason: tr("가격 부담이 적고 최근 많이 팔린 인기 상품이에요.", "It is affordable and has been popular recently."),
    matchedIntentions: tr(["가격 부담이 적어요", "최근 인기가 많아요"], ["Affordable price", "Recently popular"]),
    weakIntentions: tr(["선물로는 조금 가벼워 보일 수 있어요"], ["May feel less substantial as a gift"]),
    createdAt: T0,
    product: {
      id: "demo_p3",
      title: tr("감성 디자인 미니 블루투스 스피커 (크림)", "Mini Bluetooth Speaker (Cream)"),
      category: tr("전자기기", "Electronics"),
      brand: tr("무드톤", "MoodTone"),
      price: 49000,
      discountRate: 0.15,
      deliveryFee: 0,
      rating: 4.5,
      reviewCount: 2100,
      longTermReviewRatio: 0.2,
      recentSalesCount: 800,
      sellerName: tr("무드톤", "MoodTone"),
      sellerGrade: tr("파워", "Featured Seller"),
      attributes: tr<Record<string, string | number | boolean>>({ 색상: "크림", 방수: "생활방수", 재생시간: "12시간" }, { Color: "Cream", "Water resistance": "Splash resistant", "Playback time": "12 hours" }),
      description: tr("가격 부담이 적고 디자인이 무난해 부담 없이 고르기 좋은 인기 모델.", "A popular, affordable model with a versatile design."),
      cueSummary: {
        priceCue: "low",
        trustCue: "medium",
        popularityCue: "very_popular",
        sellerCue: "normal",
        noveltyCue: "common",
      },
    },
  },
];

export const tutorialPreferenceState: PreferenceState = {
  id: "demo_snap",
  turnIndex: 2,
  stage: "exploring",
  activeTopicIds: ["t_trust", "t_notcheap", "t_design"],
  anchorScores: {
    Functional: 0.7,
    Social: 0.5,
    Emotional: 0.6,
    Epistemic: 0.3,
    Conditional: 0.55,
    Hedonic: 0,
    Utilitarian: 0,
  },
  anchorBreakdown: {
    Functional: {
      confirmedScore: 0.55,
      contributors: [
        {
          topicLabel: tr("평점·리뷰가 믿을 만함", "Reliable ratings and reviews"),
          intensity: 0.8,
          confidence: "confirmed",
          evidenceStrength: "high",
          decisionImpact: "high",
          temporalStatus: "active",
          contribution: 0.4,
        },
      ],
    },
  },
  motivationScores: {
    Adventure: 0.3,
    Gratification: 0.35,
    Role: 0.7,
    BargainValue: 0.4,
    SocialShopping: 0.2,
    Idea: 0.3,
    Utilitarian: 0.45,
  },
  hardConstraints: tr(["평점·리뷰가 믿을 만할 것"], ["Reliable ratings and reviews"]),
  softPreferences: tr(["특별해 보이는 디자인"], ["Distinctive design"]),
  avoidances: tr(["너무 저렴해 보이는 인상"], ["An overly cheap appearance"]),
  priorityOrder: ["t_trust", "t_notcheap", "t_design"],
  uncertainty: {
    unresolvedQuestions: tr(["예산 상한이 있나요?"], ["Do you have a maximum budget?"]),
    ambiguousTopics: ["t_budget"],
    conflictIds: [],
  },
  userVisibleSummary: {
    oneSentenceSummary:
      tr("선물용으로 평점이 믿을 만하면서 너무 저렴해 보이지 않는 걸 찾고 계신 것 같아요.", "It seems that you are looking for a gift with reliable ratings that does not look too cheap."),
    needsConfirmation: true,
    chips: [
      {
        id: "t_trust",
        label: tr("평점·리뷰가 믿을 만할 것", "Reliable ratings and reviews"),
        type: "must_have",
        userEditable: true,
        evidenceCount: 3,
        displayRationale: tr("여러 번 평점·리뷰를 언급하셨어요.", "You mentioned ratings and reviews several times."),
      },
      {
        id: "t_notcheap",
        label: tr("너무 저렴해 보이지 않기", "Should not look too cheap"),
        type: "important",
        userEditable: true,
        evidenceCount: 2,
        displayRationale: tr("선물이라 저렴해 보이면 곤란하다고 하셨어요.", "You said that an overly cheap appearance would not be suitable for a gift."),
      },
      {
        id: "t_design",
        label: tr("특별해 보이는 디자인", "Distinctive design"),
        type: "nice_to_have",
        userEditable: true,
        evidenceCount: 1,
        displayRationale: tr("흔하지 않은 느낌을 선호하셨어요.", "You preferred something that feels less common."),
      },
      {
        id: "t_budget",
        label: tr("예산 20만원 이하?", "Budget under KRW 200,000?"),
        type: "uncertain",
        userEditable: true,
        evidenceCount: 1,
        displayRationale: tr("아직 예산을 명확히 말씀하지 않으셨어요.", "You have not specified a clear budget yet."),
      },
    ],
  },
  createdAt: T0,
};

export const tutorialConflict: Conflict = {
  id: "demo_conf",
  severity: "ambiguous",
  status: "open",
  conflictType: tr("가격 vs 인상", "Price vs. appearance"),
  oldAssumption: tr("너무 저렴해 보이지 않는 게 중요", "Avoiding a cheap appearance is important"),
  newSignal: tr("가격 부담이 적은 쪽에 '좋아요'", "Liked the more affordable option"),
  explanationForUser:
    tr("앞에서는 '너무 저렴해 보이지 않으면 좋겠다'고 하셨는데, 방금 가격 부담이 적은 상품에 좋아요를 누르셨어요. 어느 쪽을 더 우선할까요?", "Earlier, you said that the gift should not look too cheap, but you just liked a more affordable product. Which should take priority?"),
  suggestedResolutions: [
    { id: "r1", label: tr("가격 부담이 적은 쪽을 우선할게요", "Prioritize affordability"), action: "prefer_new", resultingStatePreview: tr("예산 절약을 더 중요하게 반영", "Give more weight to saving money") },
    { id: "r2", label: tr("그래도 너무 저렴해 보이지 않는 게 우선이에요", "Still prioritize avoiding a cheap appearance"), action: "keep_old", resultingStatePreview: tr("선물 인상(저렴해 보이지 않기) 유지", "Keep the gift-appropriate appearance criterion") },
    { id: "r3", label: tr("직접 수정", "Edit manually"), action: "manual_edit", resultingStatePreview: tr("기준을 직접 입력", "Enter the criterion directly") },
  ],
  createdAt: T0,
};
